name: rick_and_morty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route:
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  equatable: ^2.0.5
  http: ^0.13.6
  animations: ^2.0.7
  flutter_svg: ^2.0.7
  salomon_bottom_bar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator:
  build_runner:

flutter:
  uses-material-design: true
  generate: true,
  assets:
    - assets/rick.svg
    - assets/morty.svg
    - assets/Logo.svg